### ISSUE TITLE
book build fails

### ISSUE THREAD

**Issue by pieterprovoost** [iodepo/odis-arch#35]
The latest builds of the book [have failed](https://github.com/iodepo/odis-arch/runs/2952287137?check_suite_focus=true), this seems to be caused by a change in the TOC format, see https://executablebooks.org/en/latest/updates/2021-06-18-update-toc.html.

```
Running Jupyter-Book v0.11.1
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jupyter_book/cli/main.py", line 243, in build
    parse_toc_yaml(toc)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sphinx_external_toc/parsing.py", line 82, in parse_toc_yaml
    return parse_toc_data(data)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sphinx_external_toc/parsing.py", line 88, in parse_toc_data
    raise MalformedError(f"toc is not a mapping: {type(data)}")
sphinx_external_toc.parsing.MalformedError: toc is not a mapping: <class 'list'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/bin/jupyter-book", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jupyter_book/cli/main.py", line 246, in build
    f"The Table of Contents file is malformed: {exc}\n"
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jupyter_book/utils.py", line 48, in _error
    raise kind(box)
RuntimeError: 
===============================================================================

The Table of Contents file is malformed: toc is not a mapping: <class 'list'>
You may need to migrate from the old format, using:

	jupyter-book toc migrate /home/runner/work/odis-arch/odis-arch/book/_toc.yml -o /home/runner/work/odis-arch/odis-arch/book/_toc.yml

===============================================================================
```

**Comment by pieterprovoost** [comment]
The latest build passed and the book is available at https://iodepo.github.io/odis-arch/, but somehow the custom domain is no longer there in the settings. Not sure what happened but I'll try to add it again.

**Comment by pieterprovoost** [comment]
I think we are good: https://book.oceaninfohub.org/
